name: Browser Support
on:
    push:
         branches:
            - '*'
            - '!docs'
         tags:
            - '*'
jobs:
     webpack:
          name: Build
          runs-on: ubuntu-latest
          steps:
             - name: Checkout things
               uses: actions/checkout@v2
             - name: Setup Node.js v14
               uses: actions/setup-node@v2
               with:
                 node-version: '14'
             - name: Build browser version
               run: |
                 npm ci
                 npm run build
             
