name: Webpack
on:
    push:
         branches:
            - '*'
            - '!gh-pages'
         tags:
            - '*'
jobs:
     webpack:
          name: Build
          runs-on: ubuntu-latest
          steps:
             - name: Checkout things
               uses: actions/checkout@v2
             - name: Setup Node.js v14
               uses: actions/setup-node@v2
               with:
                 node-version: '14'
             - name: Install Yarn
               run: npm i -g yarn

             - name: Pull
               run: |

                git config pull.rebase false
                git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                git pull origin ${GITHUB_REF##*/}
                
             - name: Generate browser-supported dist
               run: |
                yarn install
                yarn build:dev
                yarn build:prod
             - name: Commit the dist
               run: |
                
                git add --all
                
                git commit -m "Generated browser-supported dist" -a
               continue-on-error: true
             - name: Push the dist
               uses: ad-m/github-push-action@master
               with:
                 github_token: ${{ secrets.GITHUB_TOKEN }}
                 branch: ${{ github.ref }}
               continue-on-error: true
   test_prod:
         name: Test code
         runs-on: ubuntu-latest
         needs: build
         steps:
           - name: Checkout things
             uses: actions/checkout@v2
           - name: Setup Node.js v14
             uses: actions/setup-node@v2
             with:
               node-version: '14
           - name: Run test
             run: npm run test
  test_dev:
       name: Test code
       runs-on: ubuntu-latest
       needs: build
       steps:
          - name: Checkout things
            uses: actions/checkout@v2
          - name: Setup Node.js v14
            uses: actions/setup-node@v2
            with:
              node-version: '14'
          - name: Run test
            run: export BLJS_DEV=true && npm run test
  
