name: Test

on: [push]
jobs:
   test: 
       name: Test code
       runs-on: ubuntu-latest 
       steps: 
          - name: Checkout things
            uses: actions/checkout@v2
          - name: Setup Node.js v14
            uses: actions/setup-node@v2
            with:
              node-version: '14'
          - name: Install
            run: npm install
          - name: Run test
            run: npm run test
       
